from __future__ import annotations

from dataclasses import dataclass
from typing import List

import numpy as np


@dataclass
class ToricCode:
    """Square-lattice toric code with periodic boundary conditions.

    We store qubits on edges. Horizontal edges come first, then vertical edges.
    """

    L: int

    def __post_init__(self) -> None:
        self.n = 2 * self.L * self.L
        self.n_star = self.L * self.L
        self.n_plaquette = self.L * self.L

    def mod(self, x: int) -> int:
        return x % self.L

    def h(self, x: int, y: int) -> int:
        x, y = self.mod(x), self.mod(y)
        return y * self.L + x

    def v(self, x: int, y: int) -> int:
        x, y = self.mod(x), self.mod(y)
        return self.L * self.L + y * self.L + x

    def star_index(self, x: int, y: int) -> int:
        x, y = self.mod(x), self.mod(y)
        return y * self.L + x

    def plaquette_index(self, x: int, y: int) -> int:
        x, y = self.mod(x), self.mod(y)
        return y * self.L + x

    def star_edges(self, x: int, y: int) -> List[int]:
        return [
            self.h(x, y),
            self.h(x - 1, y),
            self.v(x, y),
            self.v(x, y - 1),
        ]

    def plaquette_edges(self, x: int, y: int) -> List[int]:
        return [
            self.h(x, y),
            self.v(x + 1, y),
            self.h(x, y + 1),
            self.v(x, y),
        ]


def build_toric_pcm(L: int):
    """Build X- and Z-check matrices for the toric code."""
    code = ToricCode(L)

    Hx = np.zeros((code.n_star, code.n), dtype=np.uint8)
    Hz = np.zeros((code.n_plaquette, code.n), dtype=np.uint8)

    for x in range(L):
        for y in range(L):
            s = code.star_index(x, y)
            for q in code.star_edges(x, y):
                Hx[s, q] ^= 1

            p = code.plaquette_index(x, y)
            for q in code.plaquette_edges(x, y):
                Hz[p, q] ^= 1

    return code, Hx, Hz


def binary_rank(M: np.ndarray) -> int:
    """Rank over GF(2)."""
    A = M.copy().astype(np.uint8)
    m, n = A.shape
    r = 0
    for c in range(n):
        pivot = None
        for i in range(r, m):
            if A[i, c]:
                pivot = i
                break
        if pivot is None:
            continue
        if pivot != r:
            A[[r, pivot]] = A[[pivot, r]]
        for i in range(m):
            if i != r and A[i, c]:
                A[i] ^= A[r]
        r += 1
        if r == m:
            break
    return r


def build_logicals(code: ToricCode):
    """Canonical noncontractible logical strings."""
    n = code.n
    L = code.L

    X1 = np.zeros(n, dtype=np.uint8)
    X2 = np.zeros(n, dtype=np.uint8)
    Z1 = np.zeros(n, dtype=np.uint8)
    Z2 = np.zeros(n, dtype=np.uint8)

    for x in range(L):
        X1[code.h(x, 0)] = 1
        Z2[code.h(x, 0)] = 1

    for y in range(L):
        X2[code.v(0, y)] = 1
        Z1[code.v(0, y)] = 1

    LX = np.stack([X1, X2], axis=0)
    LZ = np.stack([Z1, Z2], axis=0)
    return LX, LZ


def gf2_row_basis(M: np.ndarray) -> np.ndarray:
    """Independent row basis over GF(2)."""
    A = M.copy().astype(np.uint8)
    m, n = A.shape
    r = 0
    for c in range(n):
        pivot = None
        for i in range(r, m):
            if A[i, c]:
                pivot = i
                break
        if pivot is None:
            continue
        if pivot != r:
            A[[r, pivot]] = A[[pivot, r]]
        for i in range(m):
            if i != r and A[i, c]:
                A[i] ^= A[r]
        r += 1
        if r == m:
            break
    return A[:r].copy()


def bits_to_int(bits: np.ndarray) -> int:
    out = 0
    for i, b in enumerate(bits):
        out |= int(b) << i
    return out


def build_logical_zero_zero_statevector(Hx: np.ndarray) -> np.ndarray:
    """Equal-weight superposition generated by the star-stabilizer subgroup."""
    basis = gf2_row_basis(Hx)
    r, n = basis.shape

    support = set()
    zero = np.zeros(n, dtype=np.uint8)

    for mask in range(1 << r):
        v = zero.copy()
        for i in range(r):
            if (mask >> i) & 1:
                v ^= basis[i]
        support.add(bits_to_int(v))

    psi = np.zeros(1 << n, dtype=complex)
    amp = 1 / np.sqrt(len(support))
    for idx in support:
        psi[idx] = amp
    return psi


def apply_binary_x_operator_to_statevector(psi: np.ndarray, x_vec: np.ndarray) -> np.ndarray:
    """Apply an X-string to a computational-basis statevector."""
    out = np.zeros_like(psi)
    mask = bits_to_int(x_vec)
    for idx, amp in enumerate(psi):
        out[idx ^ mask] = amp
    return out


def build_logical_statevector(Hx: np.ndarray, LX: np.ndarray, x: np.ndarray) -> np.ndarray:
    """Notebook-style logical basis state |x1 x2> as a full statevector."""
    x = np.asarray(x, dtype=np.uint8)
    if x.shape != (2,):
        raise ValueError("x must be a length-2 binary vector in F_2^2.")

    psi = build_logical_zero_zero_statevector(Hx)
    if x[0]:
        psi = apply_binary_x_operator_to_statevector(psi, LX[0])
    if x[1]:
        psi = apply_binary_x_operator_to_statevector(psi, LX[1])
    return psi
